name: teams_chat
description: Real-time team chat application — interview task.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.7

  # HTTP client
  dio: ^5.4.3

  # WebSocket
  web_socket_channel: ^3.0.1

  # Local storage
  shared_preferences: ^2.2.3

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
